= School Timetabling (Java, Quarkus, Maven or Gradle)

Assign lessons to timeslots and rooms to produce a better schedule for teachers and students.

* <<run,Run the application>>
* <<package,Run the packaged application>>
* <<native,Run it native>>

[[run]]
== Run the application

. Git clone the optaplanner-quickstarts repo and navigate to this directory:
+
[source, shell]
----
$ git clone https://github.com/kiegroup/optaplanner-quickstarts.git
...
$ cd optaplanner-quickstarts/use-cases/school-timetabling
----

. Start the application with Maven:
+
[source, shell]
----
$ mvn quarkus:dev
----
+
or with Gradle:
+
[source, shell]
----
$ gradle quarkusDev
----

. Visit http://localhost:8080 in your browser.

. Click on the *Solve* button.

Then try _live coding_:

. Make some changes in the source code.
. Refresh your browser (F5).

Notice that those changes are immediately in effect.


[[package]]
== Run the packaged application

When you're done iterating in `quarkus:dev` mode,
package the application to run as a conventional jar file.

. Build it with Maven:
+
[source, shell]
----
$ mvn package
----
+
or with Gradle:
+
[source, shell]
----
$ gradle clean build
----

. Run the Maven output:
+
[source, shell]
----
$ java -jar ./target/quarkus-app/quarkus-run.jar
----
+
or the Gradle output:
+
[source, shell]
----
$ java -jar ./build/quarkus-app/quarkus-run.jar
----
+
[NOTE]
====
To run it on port 8081 instead, add `-Dquarkus.http.port=8081`.
====

. Visit http://localhost:8080 in your browser.

. Click on the *Solve* button.

[[native]]
== Run it native

To increase startup performance for serverless deployments,
build the application as a native executable:

. https://quarkus.io/guides/building-native-image#configuring-graalvm[Install GraalVM and gu install the native-image tool]

. Compile it natively. This takes a few minutes:
+
[source, shell]
----
$ mvn package -Dnative -DskipTests
----

. Run a database. By default, `application.properties` is configured for H2:
.. Download the http://www.h2database.com/html/download.html[H2 database] (Platform-independent zip) and unzip it.
.. Start the H2 server with the option `-ifNotExists` (not recommended in production):
+
[source, shell]
----
$ cd h2/bin
$ java -cp h2*.jar org.h2.tools.Server -ifNotExists
----

. Run the native executable:
+
[source, shell]
----
$ ./target/*-runner
----

. Visit http://localhost:8080 in your browser.

. Click on the *Solve* button.

== More information

Visit https://www.optaplanner.org/[www.optaplanner.org].
